### ISSUE TITLE
"GlucoseFromRaw.swift" not found

### ISSUE THREAD

**Issue by Nnk2** [dabear/LibreTransmitter#1]
Hello dabear, 

Thank you for posting this plugin.

Unfortunately, I keep getting an Xcode compile error, trying to load the LibreTransmitter plugin (through a combined workspace) to the Loop app, running on my iPhone X on iOS 14.3:

Build input file cannot be found: '....._/LibreTransmitter-main/LibreSensor/GlucoseAlgorithm/GlucoseFromRaw.swift’_

A search for "GlucoseFromRaw.swift" on my Mac does not find anything either. 
Do I need to preload any specific libraries or kits to make this work for by FSL/MiaoMioa? 

(Apologies if I missed anything myself ..)

**Comment by gui-dos** [comment]
I think the @bubbledevteam's implementation in https://github.com/bubbledevteam/bubble-client-swift/blob/5e5885feac5e23dcdce739bdf3cd846b81a048dc/BubbleClient/NFCManager.swift#L823-L850 share the same code base.

**Comment by Nnk2** [comment]
> I think that @bubbledevteam's implementation in https://github.com/bubbledevteam/bubble-client-swift/blob/5e5885feac5e23dcdce739bdf3cd846b81a048dc/BubbleClient/NFCManager.swift#L823-L850 and xdripswift's one (https://github.com/JohanDegraeve/xdripswift/blob/d0c996b58a2f99e48f0d1da774db12e78ce74985/xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreMeasurement.swift#L148) share the same code base.

Thank you Guido.

Unfortunately, that version also does not seem to contain the  GlucoseFromRaw.swift code and fails on my Xcode setup ...

**Comment by Nnk2** [comment]
Just found the readme comment, that this branch that it indeed comes without a GlucoseFromRaw.swift file... I guess I can close this comment (and need to read more before posting). My apologies.

**Comment by dabear** [comment]
Closing this
