### ISSUE TITLE
PreLibre2 - Large Tuple Violation during compilation

### ISSUE THREAD

**Issue by edddeduck** [dabear/LibreTransmitter#12]
PreLibre2 -> LibreBLEResoponce - Line 219 - `typealias LibreBLEResponse = (age: Int, trend: [Measurement], history: [Measurement], crcVerified: Bool)` 

I get a compile error on this line using Xcode 14.2 and MacOS 13.1 using an M1 iMac

The error is `Large Tuple Violation: Tuples should have at most 2 members. (large_tuple)` this seems to come from the swiftlint library analysis (swiftlint--0.50.3.arm64_ventura) however the fact the error is displayed (instead of the missing library error) indicates the library is loading as expected.

**Comment by dabear** [comment]
It's probably due to  a "newish" best-practices. You can ignore it for now by googling "How to Disable SwiftLint Rules?". Will probably fix it in due time

**Comment by edddeduck** [comment]
For anyone else reading in the future.

This worked by adding ~/Code/LoopWorkspace/LibreTransmitter/LibreSensor/SensorContents/PreLibre2.swift to the "excluded:" files inside the .swiftlint.yml file for the Libre subproject.

A quick google should assist in the specifics.
