### ISSUE TITLE
Build still fails (for me)

### ISSUE THREAD

**Issue by Nnk2** [dabear/LibreTransmitter#2]
Hello dabear, Others, 

Again, thank you for creating this branch and apologies for having to reach out (as an Xcode newbie): 
This Branch is exactly what I am looking for, if I can get it to compile/load to Loop.

After finding GlucoseFromRaw.swift elsewhere, copying that to the GlucoseAlgorithm folder, **Xcode now gives me a "cannot find LoopKit" module error.**

Adding the LoopKit-Master and Loop-master projects to my workspace, compiling them and copying LoopKit and LoopKitUI framework files to LibreTransmitter-main subfolders, just gives more errors.

Is there any way you can help me/us load this plugin successfully to Loop?
(Or share a LibreTransmitter.xcodeproj or .xcworkspace file that will compile?)

**Comment by dabear** [comment]
Dude. This is experimental and not doing general support here. It is neither compatible with loop master or dev . It will become compatible with dev when I find the time. But still no user support here
